### Exercise 3: For this exercise you will use financial data from Yahoo web site. 

<ul>
<li>Get the Data: Go to Yahoo! Finance and download daily data from a stock that has at least eight years of data, making sure it goes from earlier to later. 
<li> Create the time series of daily log returns of the stock price. Do the same for volume data (i.e., create the time series of daily log changes in volume).
<li> Next, set up a linear regression model that uses the past two returns to predict the next return. Run it and see if you can make any money with it. Try it for both stock returns and volumes. 
</ul>

In [2]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

### Read stock data from .csv file

In [3]:
# read stock values from .csv file
df_stocks = pd.read_csv("GSPC.csv")
df_stocks.head()

Date         Open         High          Low        Close  \
0  2010-01-04  1116.560059  1133.869995  1116.560059  1132.989990   
1  2010-01-05  1132.660034  1136.630005  1129.660034  1136.520020   
2  2010-01-06  1135.709961  1139.189941  1133.949951  1137.140015   
3  2010-01-07  1136.270020  1142.459961  1131.319946  1141.689941   
4  2010-01-08  1140.520020  1145.390015  1136.219971  1144.979980   

     Adj Close      Volume  
0  1132.989990  3991400000  
1  1136.520020  2491020000  
2  1137.140015  4972660000  
3  1141.689941  5270680000  
4  1144.979980  4389590000

In [4]:
df_stocks = df_stocks[['Date', 'Adj Close', 'Volume']]
df_stocks.head()

Date    Adj Close      Volume
0  2010-01-04  1132.989990  3991400000
1  2010-01-05  1136.520020  2491020000
2  2010-01-06  1137.140015  4972660000
3  2010-01-07  1141.689941  5270680000
4  2010-01-08  1144.979980  4389590000

In [54]:
from sklearn.linear_model import LinearRegression
from sklearn import model_selection, preprocessing

In [73]:
#df = quandl.get("WIKI/AMZN")
df = df_stocks
df = df[['Adj Close']]
df.tail()

Adj Close
2063  2747.330078
2064  2752.010010
2065  2712.919922
2066  2716.939941
2067  2711.929932

#### Forecast for next 10 days

In [74]:
forecast_out = int(10)
df['Prediction'] = df[['Adj Close']].shift(-forecast_out)

In [75]:
X = np.array(df.drop(['Prediction'], 1))
#X = preprocessing.scale(X)

X_forecast = X[-forecast_out:]
X = X[:-forecast_out]

y = np.array(df['Prediction'])
y = y[:-forecast_out]

In [76]:
X = np.array(df.drop(['Prediction'], 1))

In [77]:
X_forecast

array([[ 2738.969971],
       [ 2786.570068],
       [ 2783.02002 ],
       [ 2765.310059],
       [ 2749.47998 ],
       [ 2747.330078],
       [ 2752.01001 ],
       [ 2712.919922],
       [ 2716.939941],
       [ 2711.929932]])

In [45]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size = 0.2)

In [70]:
y_test

array([  50.09,   33.68,  752.61, ...,   41.01,  204.38,   38.01])

In [46]:
# Training
clf = LinearRegression()
clf.fit(X_train,y_train)

# Testing
confidence = clf.score(X_test, y_test)
print("confidence: ", confidence)

confidence:  0.989975165338


In [71]:
X_forecast

array([[ 4.21379342],
       [ 4.31435785],
       [ 4.44429505],
       [ 4.48238009],
       [ 4.43590283],
       [ 4.50581431],
       [ 4.55762561],
       [ 4.5641687 ],
       [ 4.61836254],
       [ 4.69641732],
       [ 4.66096374],
       [ 4.66263507],
       [ 4.59507057],
       [ 4.61925155],
       [ 4.70232033],
       [ 4.75221138],
       [ 4.77838373],
       [ 4.80277807],
       [ 4.89889747],
       [ 4.96823998],
       [ 4.93193295],
       [ 4.94196095],
       [ 4.91109464],
       [ 4.87325852],
       [ 4.77813481],
       [ 4.92599439],
       [ 4.90945887],
       [ 4.77518331],
       [ 4.60257379],
       [ 4.81700218]])

In [47]:
forecast_prediction = clf.predict(X_forecast)
print(forecast_prediction)

[ 1468.2991062   1498.32145266  1537.1127023   1548.48255133  1534.60730139
  1555.47856488  1570.94623065  1572.89959407  1589.07853891  1612.38089056
  1601.79663334  1602.2955903   1582.12498978  1589.34394154  1614.14316408
  1629.03756015  1636.85101383  1644.13366223  1672.82899549  1693.53040129
  1682.69135754  1685.6850993   1676.47031969  1665.1747834   1636.77670109
  1680.91846791  1675.98197884  1635.89556433  1584.36498805  1648.38010444]
